Milestone paid email shows incorrect value of amount
Giveth/feathers-giveth pull request #251
Opened 2020-11-10 16:41 UTC by mohammadranjbar

In previous code the donated amount read from `currentBalance` that I saw it was `'0'` for all `milestones.donationCounters` and I think the correct field is `totalDonated ` as in the https://github.com/Giveth/giveth-dapp show that field and beside that check this milestone :  https://feathers.beta.giveth.io/milestones/5b3a5b0bdf629170d472b3cf
That you see the `totalDonated` value is:
```
 "donationCounters": [
        {
            "_id": "5cdc2226a16c6c16214d29ef",
            "name": "ETH",
            "address": "0x0",
            "decimals": "6",
            "symbol": "ETH",
            "totalDonated": "221720630000000000",
            "currentBalance": "0",
            "donationCount": 1
        }
    ],

```

Fix #246

2020-11-11 07:22 UTC, aminlatifi commented
`totalDonated` is not appropriate value, user may collect/disburse multiple time. We create conversation record on collect/disburse which has correct value, see how can use it for this purpose.

2020-11-11 07:23 UTC, aminlatifi requested changes
`totalDonated` is not appropriate value, user may collect/disburse multiple time. We create conversation record on collect/disburse which has correct value, see how can use it for this purpose.

2020-11-11 07:35 UTC, mohammadranjbar commented
This conversions are related to above milestone, and I have no idea how we can calculate paid amount from that,
```
{
    "total": 2,
    "limit": 25,
    "skip": 0,
    "data": [
        {
            "_id": "5b450bfafd38ee2a3efd9ad3",
            "milestoneId": "5b3a5b0bdf629170d472b3cf",
            "message": "",
            "messageContext": "NeedsReview",
            "ownerAddress": "0x53516256736bEbf6b5ACd3aBA9994A064247cF9D",
            "performedByRole": "Milestone Owner",
            "createdAt": "2018-07-10T19:41:46.367Z",
            "updatedAt": "2018-07-10T19:41:46.367Z",
            "items": [],
            "mined": false,
            "_include": [
                "owner"
            ],
            "owner": {
                "address": "0x53516256736bEbf6b5ACd3aBA9994A064247cF9D",
                "name": "Vojtech Simetka",
                "email": "vojtech@giveth.io",
                "giverId": 24,
                "commitTime": 259200,
                "avatar": "https://feathers.beta.giveth.io/uploads/6ceac1fdd83eab5ce3399a1e9e3cb89f9f5999a86e50139a838864aedae6559e.jpeg",
                "createdAt": "2018-06-30T10:07:27.254Z",
                "updatedAt": "2020-06-22T11:20:56.784Z",
                "linkedin": "https://simetka.cz",
                "url": "",
                "prevUrl": "/ipfs/QmQpDQQJfYoBeEZ7o9rCBebrXvyNZDQc6zt4Hdwo7nkN3k"
            }
        },
        {
            "_id": "5b53be8728f2557bafc23fc8",
            "mined": false,
            "milestoneId": "5b3a5b0bdf629170d472b3cf",
            "message": "",
            "items": [],
            "messageContext": "NeedsReview",
            "txHash": "0xd747c70291a469196bbea9866419c65cf033c7fa11cc7456a764bb5b5a786199",
            "ownerAddress": "0x361e160d7e89888476d5094227443cAD4a4154C3",
            "performedByRole": "Milestone Owner",
            "createdAt": "2018-07-21T23:15:19.824Z",
            "updatedAt": "2018-07-21T23:15:19.824Z",
            "_include": [
                "owner"
            ],
            "owner": {
                "address": "0x361e160d7e89888476d5094227443cAD4a4154C3",
                "createdAt": "2018-07-10T17:25:09.007Z",
                "updatedAt": "2018-07-10T17:25:33.927Z",
                "email": "gentlemandonadams@gmail.com",
                "giverId": 0,
                "name": "Don Adams"
            }
        }
    ]
}
```

I think it would be great if we have a call and make it clear to me  the business and logic of this part

2020-11-13 14:48 UTC, mohammadranjbar commented
@aminlatifi 
I think a lot about that and the the guides you told me in telegram, but as I reaching a idea I'm getting confused and lost every thing, 
I would appreciate if we can do some tasks like this pair, it's a good way for Onboarding

2020-11-22 06:46 UTC, mohammadranjbarz commented
I think the payment amount of last conversation  of milestone with `messageContext:payment`  is appropriate value for sending in email, 
@aminlatifi do you agree with me ( in my case the last conversation with amount `5.02027 ETH` is the last collected amount) ?

![image](https://user-images.githubusercontent.com/9850545/99897016-0d5a8d00-2cab-11eb-81c4-08377f243e06.png)

2020-11-22 07:38 UTC, aminlatifi commented
> I think the payment amount of last conversation of milestone with `messageContext:payment` is appropriate value for sending in email,
> @aminlatifi do you agree with me ( in my case the last conversation with amount `5.02027 ETH` is the last collected amount) ?
> 
> ![image](https://user-images.githubusercontent.com/9850545/99897016-0d5a8d00-2cab-11eb-81c4-08377f243e06.png)

Let's discuss under #246

2020-11-24 13:08 UTC, mohammadranjbarz commented
@aminlatifi 
I created another pull request so I delete this one

2020-11-24 13:08 UTC, closed without merging