add functions to calculate conversion rates hourly
Giveth/feathers-giveth pull request #287
Opened 2020-12-03 14:47 UTC by mdehghani

related to issue #1556 in giveth-dapp

2020-12-06 09:51 UTC, aminlatifi requested changes

2020-12-06 09:51 UTC, aminlatifi commented on src/services/conversionRates/getConversionRatesService.js
> +      .patch(null, { timestamp, rates, symbol }, {query: {timestamp, symbol}, mongoose: {upsert: true, writeResult: true}})
What's the reason of changing this line?

2020-12-06 09:51 UTC, aminlatifi commented on src/services/conversionRates/getConversionRatesService.js
> +  let decimals = toToken && toToken.decimals ? toToken.decimals : 2;
According to convention, `const` variable type is better candidate. Please use `let` when the variable will be modified after.

2020-12-10 14:35 UTC, mdehghani commented
@aminlatifi please take a look

2020-12-10 21:44 UTC, merged